Fix build against 9.6
parser/keywords.h is now common/keywords.h

The regression expected output files need a new variant because plpgsql
ERRORs will now show an extra CONTEXT line. The net diff for the two
added _1.out files is:

```
--- sql/pgq_node/expected/pgq_node_test.out	2013-02-08 10:44:34.000000000 +0100
+++ sql/pgq_node/expected/pgq_node_test_1.out	2016-09-28 12:36:52.311636581 +0200
@@ -269,6 +269,7 @@

 select * from pgq_node.is_root_node('cqueue');
 ERROR:  queue does not exist: cqueue
+CONTEXT:  PL/pgSQL function pgq_node.is_root_node(text) line 19 at RAISE
 select * from pgq_node.get_consumer_state('bqueue', 'random_consumer');
  ret_code | ret_note | node_type | node_name | completed_tick | provider_node | provider_location | paused | uptodate | cur_error
 ----------+----------+-----------+-----------+----------------+---------------+-------------------+--------+----------+-----------

--- sql/pgq_coop/expected/pgq_coop_test.out	2013-02-08 10:44:34.000000000 +0100
+++ sql/pgq_coop/expected/pgq_coop_test_1.out	2016-09-28 12:36:52.311636581 +0200
@@ -137,6 +137,7 @@

 select pgq_coop.unregister_subconsumer('testqueue', 'maincons', 'subcons2', 0);
 ERROR:  subconsumer has active batch
+CONTEXT:  PL/pgSQL function pgq_coop.unregister_subconsumer(text,text,text,integer) line 42 at RAISE
 select pgq_coop.unregister_subconsumer('testqueue', 'maincons', 'subcons2', 1);
  unregister_subconsumer
 ------------------------
```